channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=21.2.4
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.2
  - numpy==2.0.2
  - pandas==2.3.3
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
